name: CI                          # 워크플로우 이름 (GitHub UI에 표시)
on: [push]                        # 이벤트: push가 발생할 때 실행
jobs:                             # 작업들 정의
  build:                          # build라는 이름의 작업
    runs-on: ubuntu-latest        # 실행 환경: 우분투 최신 버전

  steps:                          # 작업 단계들
    - uses: actions/checkout@v2   # 코드를 runner로 가져오는 GitHub공식 action
    - run: echo "Hello,DevOps!"
